pipeline {
    agent any
    environment {
      ARTIFACTORY_SERVER = "192.168.0.17" 
      SERVER_URL = "http://192.168.0.17:8081/artifactory"
      CREDENTIALS = "1234"
      }
    
    stages {
        stage ('Clone') {
            steps {
                git branch: 'master', url: "git@github.com:najitestech/SimpleCustomerApp.git"
            }
        }
        stage('Compile Stage') {
          steps {
            withMaven(maven : 'maven-3.6.1') {
                sh 'mvn clean compile'
            }
          }
        }
      stage ('Artifactory configuration') {
            steps {
                rtServer (
                    id: "ARTIFACTORY_SERVER",
                    url: SERVER_URL,
                    credentialsId: CREDENTIALS
                )

                rtMavenDeployer (
                    id: "MAVEN_DEPLOYER",
                    serverId: "ARTIFACTORY_SERVER",
                    releaseRepo: "example-repo-local",
                    snapshotRepo: "example-repo-local"
                )

                rtMavenResolver (
                    id: "MAVEN_RESOLVER",
                    serverId: "ARTIFACTORY_SERVER",
                    releaseRepo: "my-maven-repo",
                    snapshotRepo: "my-maven-repo"
                )
            }
        }  
      stage ('Publish build info') {
            steps {
                //rtPublishBuildInfo (  
                    serverId: "ARTIFACTORY_SERVER"
                //)
            }
        }
    }  
 }
