pipeline {
    agent any
    
    stages {
        stage('Compile Stage') {
          steps {
            withMaven(maven : 'maven-3.6.1') {
                sh 'mvn SimpleCustomerApp/clean compile'
            }
          }
        } 
      }  
    }  
